apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonAnnotations:
  add-on.kubeflow.oraclecloud.com/https: 1.0.0

components:
- ../../../oci/common/istio/kubeflow-istio-resources/overlays/https
