apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1beta1
      kind: MutatingWebhookConfiguration
      name: admission-webhook-mutating-webhook-configuration
    # Workaround for manifests bug https://github.com/kubeflow/manifests/issues/1894
    # The service name isn't properly being replaced from the params.yaml. This sets it to the
    # value it should be.
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/name
        value: admission-webhook-service
