apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: pipeline-install-config
  envs: 
  - params.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
# - name: kubeflow-pipelines-profile-controller-code
#   behavior: replace
#   files:
#   - sync.py
# - name: workflow-controller-configmap
#   behavior: replace
#   files:
#   - workflow-controller.ConfigMap.yaml

secretGenerator:
- name: mlpipeline-minio-artifact
  behavior: replace
  envs:
  - minio.env
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patches/ml-pipeline-ui.Deployment.yaml
- patches/ml-pipeline.Deployment.yaml
- patches/minio.Deployment.yaml


# patches:
# - patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env/-"
#       value:
#         name: MINIO_SSL
#         valueFrom:
#           configMapKeyRef:
#             optional: true
#             key: minioSSL
#             name: pipeline-install-config
#   target:
#     kind: Deployment
#     namespace: kubeflow
#     name: kubeflow-pipelines-profile-controller
# - patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env/-"
#       value:
#         name: MINIO_PORT
#         valueFrom:
#           configMapKeyRef:
#             optional: true
#             key: minioServicePort
#             name: pipeline-install-config
#   target:
#     kind: Deployment
#     namespace: kubeflow
#     name: kubeflow-pipelines-profile-controller
# - patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env/-"
#       value:
#         name: MINIO_HOST
#         valueFrom:
#           configMapKeyRef:
#             optional: true
#             key: minioServiceHost
#             name: pipeline-install-config
#   target:
#     kind: Deployment
#     namespace: kubeflow
#     name: kubeflow-pipelines-profile-controller
