apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


# Patch mlpipelines to store artifacts directly into OCI Object Storage
# writes are direct and then reads are through the Minio Gateway as storage is private
# and Minio acts as the client.
configMapGenerator:
- name: pipeline-install-config
  envs: 
  - params.env
  behavior: merge
# patch workflow controller that defines config for each namespace 
# to use direct storage on OCI
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json

secretGenerator:
- name: mlpipeline-minio-artifact
  behavior: replace
  envs:
  - minio.env
generatorOptions:
  disableNameSuffixHash: true

# the minio Deployment is patched to use minio in gateway mode
# note that gateway mode is deprecated on Minio, so this uses a frozen version of Minio
# Also note that the last official version of Minio to support gateway mode does not support 
# custom regions, so only the home region can be used.
# patched version is being worked on.
patches:
- path: patches/ml-pipeline-ui.Deployment.yaml
- path: patches/ml-pipeline.Deployment.yaml
- path: patches/minio.Deployment.yaml
