apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

bases:
- ../../../upstream/common/dex/base

configMapGenerator:
- name: dex-idcs
  files:
    - config.yaml
generatorOptions:
  disableNameSuffixHash: true
  
patchesStrategicMerge:
- patches/dex.Deployment.yaml
  