apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/envFrom/-"
      value: 
        configMapRef:
          name: oidc-authservice-parameters-letsencrypt
  target:
    kind: StatefulSet
    namespace: istio-system
    name: authservice

# Add the env overrides for authservice to work with letsencrypt http01 challenge 
# (i.e. it needs to whitelist the /.well-known/* endpoints where the challenge is 
# served so letsencrypt can reach it without auth)
configMapGenerator:
- name: oidc-authservice-parameters-letsencrypt
  namespace: istio-system
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true
