apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# disable local MySQL and create service to External Name pointing 
# to the FQDN of the managed MySQL database
# also create new secret for MySQL access
patchesStrategicMerge:
- patches/disable-local-mysql.yaml
- mysql.Service.yaml

patches:
- patch: |-
    - op: remove
      path: "/spec/selector"
  target:
    kind: Service
    namespace: kubeflow
    name: mysql
- patch: |-
    - op: remove
      path: "/spec/ports"
  target:
    kind: Service
    namespace: kubeflow
    name: mysql

secretGenerator:
- name: mysql-secret
  behavior: replace
  envs:
  - mysql.env

generatorOptions:
  disableNameSuffixHash: true
