apiVersion: v1
kind: Service
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql
  namespace: kubeflow
spec:
  externalName: mysql.subnet1.cluster.oraclevcn.com
  type: ExternalName
