apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# This is a bug fix. 
# It disabled istio sidecar injection on the Katib experiment pods.
patchesStrategicMerge:
- trial-templates.ConfigMap.yaml
