apiVersion: v1
kind: ConfigMap
metadata:
  name: config-certmanager
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-certmanager
    app.kubernetes.io/version: "1.7.0"
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
data:
  issuerRef: |
    kind: ClusterIssuer
    name: letsencrypt-prod-issuer