apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../upstream/example/

components:
- ../../oci/common/istio/istio-install/overlays/oci-load-balancer

# patch to fix admission webhook service name 
- ../../oci/apps/admission-webhook/cert-manager

# patch to fix katib trial templates / remove istio sidecar injector
- ../../oci/apps/katib/trial-experiment-fix

# Install metrics server, used for HorizontalPodAutoscalers and ClusterAutoscaler
- ../../oci/metrics-server