apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../../upstream/common/cert-manager/cert-manager/base
- ../../upstream/common/cert-manager/kubeflow-issuer/base
# Istio
- ../../upstream/common/istio-1-11/istio-crds/base
- ../../upstream/common/istio-1-11/istio-namespace/base
# - ../../oci/common/istio-1-11/istio-install/overlays/sidecar-injector
- ../../upstream/common/istio-1-11/istio-install/base

# OIDC Authservice
- ../../upstream/common/oidc-authservice/base
# Dex
- ../../upstream/common/dex/overlays/istio
# KNative
- ../../upstream/common/knative/knative-serving/overlays/gateways
- ../../upstream/common/knative/knative-eventing/base
- ../../upstream/common/istio-1-11/cluster-local-gateway/base
# Kubeflow namespace
- ../../upstream/common/kubeflow-namespace/base
# Kubeflow Roles
- ../../upstream/common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../../upstream/common/istio-1-11/kubeflow-istio-resources/base


# Kubeflow Pipelines
- ../../upstream/apps/pipeline/upstream/env/platform-agnostic-multi-user
# KFServing
- ../../upstream/apps/kfserving/upstream/overlays/kubeflow
# Katib
- ../../upstream/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../../upstream/apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../../upstream/apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- ../../upstream/apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- ../../upstream/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../../upstream/apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../../upstream/apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
- ../../upstream/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- ../../upstream/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../../upstream/apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../../upstream/common/user-namespace/base

# KServe
- ../../upstream/contrib/kserve/kserve
- ../../upstream/contrib/kserve/models-web-app/overlays/kubeflow

components:
- ../../oci/common/istio-1-11/istio-install/overlays/oci-load-balancer

# patch to fix katib trial templates / remove istio sidecar injector
- ../../oci/apps/katib/trial-experiment-fix
