apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Create a Self signing Issuer, and create a self-signed TLS cert for the KubeFlow Gateway
# This is used when using the IP only. Use one of the letsencrypt methods to provision certificates
# for a domain name
resources:
- kubeflow-gw.Certificate.yaml
- istio-ns.Issuer.yaml

patches:
- path: patches/kubeflow.Gateway.yaml
