apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


configMapGenerator:
- name: dex-idcs
  namespace: auth
  files:
    - config.yaml=idcs-config.yaml

generatorOptions:
  disableNameSuffixHash: true
  
patchesStrategicMerge:
- patches/dex.Deployment.yaml
