apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- cert-manager-webhook-oci.yaml

components:
- ../../../oci/common/istio-1-14/kubeflow-istio-resources/overlays/letsencrypt-dns01
# - ../../../oci/common/oidc-authservice/overlays/letsencrypt
- ../../../oci/apps/kserve/domain

# net-certmanager is used to issue wildcard certificates for the namespace sub-domains 
# using the let's encrypt ClusterIssuer with DNS01 challenge
- ../../../oci/apps/kserve/net-certmanager
