apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-irisv2"
spec:
  predictor:
    sklearn:
      protocolVersion: "v2"
      storageUri: "https://objectstorage.us-sanjose-1.oraclecloud.com/p/xKuRUl7hf7BE3t0G4aPakNb4n73cCrZ1zTNQadtW2XBzJFzhT6j8aIsWbvViir7C/n/bigdatadatasciencelarge/b/epleroy-public-models/o/model.joblib"

