# The katib-external-db manifest does not create the necessary katib ui virtual service 
# and does not apply the configurations from katib-cert-manager, 
# which the katib-with-kubeflow manifest does. 
# This manifest extends off of the katib-with-kubeflow manifest 
# and applies the necessary patch for katib to use an external db
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# set external DB credentials on Katib and uses an init container to create the database if it does not exist
# Remove the original mysql deployment 
patches:
- path: patches/katib-db-manager.Deployment.yaml
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: katib-mysql
      namespace: kubeflow
    $patch: delete
  target:
    kind: Deployment
    name: katib-mysql
    namespace: kubeflow
- patch: |-
    kind: Secret
    metadata:
      name: katib-mysql-secrets
      namespace: kubeflow
    $patch: delete
  target:
    kind: Secret
    name: katib-mysql-secrets
    namespace: kubeflow
- patch: |-
    kind: PersistentVolumeClaim
    metadata:
      name: katib-mysql
      namespace: kubeflow
    $patch: delete
  target:
    kind: PersistentVolumeClaim
    name: katib-mysql
    namespace: kubeflow
- patch: |-
    kind: Service
    metadata:
      name: katib-mysql
      namespace: kubeflow
    $patch: delete
  target:
    kind: Service
    name: katib-mysql
    namespace: kubeflow
