apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# patches the KubeFlow service to make it a Load Balancer type, 
# setting the annotations to provision a flex load balancer with 10-400MBs bandwidth
patches:
- path: patches/istio-ingressgateway.Service.yaml
