apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-gateway-cert-letsencrypt-wildcard
  namespace: istio-system
spec:
  secretName: kubeflow-gateway-letsencrypt-wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ${OCI_KUBEFLOW_DOMAIN_NAME}
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: \"*.${OCI_KUBEFLOW_DOMAIN_NAME}\"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - server auth
    - client auth
  # # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - \"*.${OCI_KUBEFLOW_DOMAIN_NAME}\"
    - ${OCI_KUBEFLOW_DOMAIN_NAME}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod-wildcard-issuer
    kind: ClusterIssuer
