apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-wildcard-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: ${OCI_KUBEFLOW_DOMAIN_ADMIN_EMAIL}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-wildcard

    solvers:
      - dns01:
          webhook:
            groupName: acme.oci.dns
            solverName: oci
            config:
              ociProfileSecretName: oci-profile
              compartmentOCID: ${OCI_KUBEFLOW_DNS_ZONE_COMPARTMENT_OCID}
