apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: katib-db-manager
          env:
          - name: DB_NAME
            value: mysql
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          # - name: KATIB_MYSQL_DB_DATABASE
          #   value: katibdb
          - name: KATIB_MYSQL_DB_HOST
            value: mysql
              # configMapKeyRef:
              #   name: pipeline-install-config
              #   key: dbHost
          # - name: KATIB_MYSQL_DB_PORT
          #   valueFrom:
          #     configMapKeyRef:
          #       name: pipeline-install-config
          #       key: dbPort
