apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
$patch: delete
